name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildLinux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
      
  buildWindows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
